name: Terraform Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_TERRAFORM }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_TERRAFORM }}

jobs:
  terraform:
    name: Plan / Apply